export const FETCH_LISTS_LOADING = "FETCH_LISTS_LOADING";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE";

export const SEARCH_TASK = "SEARCH_TASK";

export const UPDATING_TASK_LOADING = "UPDATING_TASK_LOADING";
export const UPDATING_TASK_FAILURE = "UPDATING_TASK_FAILURE";
export const UPDATING_TASK_SUCCESS = "UPDATING_TASK_SUCCESS";
